NAME           NO_TITLE
*****************************************************
* REMARK: Generated by LSwriteMPSFile() routine for 
* a maximization type problem.
*
* The objective coefficients have flipped signs. 
* Interpret the objective value from the solution of
* this model accordingly.
*****************************************************
ROWS
 N       OBJ
 L  R0000000
 L  R0000001
 L  R0000002
COLUMNS
    B0000000       OBJ  -1
    B0000000  R0000000  -1
    B0000000  R0000001  1
    C0000001       OBJ  -2
    C0000001  R0000000  1
    C0000001  R0000001  -3
    INT0000B  'MARKER'                 'INTORG'
    I0000002       OBJ  -3
    I0000002  R0000000  1
    I0000002  R0000001  1
    INT0000E  'MARKER'                 'INTEND'
RHS
    RHS1      R0000000  20
    RHS1      R0000001  30
    RHS1      R0000002  1
BOUNDS
 BV BND1      B0000000
 LO BND1      I0000002  0
QSECTION           OBJ
    B0000000  B0000000  33
    B0000000  C0000001  -6
    C0000001  C0000001  22
    C0000001  I0000002  -11.5
    I0000002  I0000002  11
QSECTION      R0000002
    B0000000  B0000000  2
    C0000001  C0000001  2
    I0000002  I0000002  2
ENDATA
